-- ============================================================
-- Migration 010 — Spain Signals Engine
-- Run in Supabase SQL Editor
-- ============================================================

-- Add Spain metadata fields to markets table
ALTER TABLE markets
  ADD COLUMN IF NOT EXISTS super_category  text,        -- 'SPAIN' for Spain-specific markets
  ADD COLUMN IF NOT EXISTS spain_category  text;        -- POLITICA_ES | ECONOMIA_ES | DEPORTE_ES | CULTURA_ES | LA_PLAZA

-- Indexes for Spain filter
CREATE INDEX IF NOT EXISTS idx_markets_super_category ON markets(super_category) WHERE super_category IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_markets_spain_category ON markets(spain_category) WHERE spain_category IS NOT NULL;

-- Useful composite for Spain filtered queries
CREATE INDEX IF NOT EXISTS idx_markets_spain_active ON markets(super_category, status, close_date)
  WHERE super_category = 'SPAIN' AND status = 'ACTIVE';

COMMENT ON COLUMN markets.super_category IS 'Top-level market origin tag. SPAIN = generated by Spain Signals Engine.';
COMMENT ON COLUMN markets.spain_category IS 'Spain-specific subcategory: POLITICA_ES, ECONOMIA_ES, DEPORTE_ES, CULTURA_ES, LA_PLAZA, INTERNACIONAL_ES.';
