// ============================================================
// Spain Source Registry — Spanish media RSS sources
// Extends the global source registry with Spain-specific feeds.
// Focused on national, regional, cultural and current affairs.
// ============================================================

export const SPAIN_SOURCES = [

  // ── NATIONAL BROADCAST / PUBLIC ───────────────────────────────────────────
  {
    key:            'rtve_noticias',
    label:          'RTVE — Noticias',
    url:            'https://www.rtve.es/api/programas/noticiarios/contenidos.rss',
    type:           'rss',
    category:       'ACTUALIDAD',
    spainCategory:  'ACTUALIDAD_ES',
    language:       'es',
    credibility:    0.92,
    refreshMinutes: 15,
    active:         true,
  },
  {
    key:            'rtve_espana',
    label:          'RTVE — España',
    url:            'https://www.rtve.es/noticias/20100413/rss/noticias-espana.xml',
    type:           'rss',
    category:       'POLITICA',
    spainCategory:  'POLITICA_ES',
    language:       'es',
    credibility:    0.92,
    refreshMinutes: 20,
    active:         true,
  },

  // ── NATIONAL NEWSPAPERS ───────────────────────────────────────────────────
  {
    key:            'elpais_cultura',
    label:          'El País — Cultura',
    url:            'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/cultura/portada',
    type:           'rss',
    category:       'CULTURA',
    spainCategory:  'CULTURA_ES',
    language:       'es',
    credibility:    0.88,
    refreshMinutes: 30,
    active:         true,
  },
  {
    key:            'elpais_sociedad',
    label:          'El País — Sociedad',
    url:            'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/sociedad/portada',
    type:           'rss',
    category:       'SOCIEDAD',
    spainCategory:  'SOCIEDAD_ES',
    language:       'es',
    credibility:    0.88,
    refreshMinutes: 30,
    active:         true,
  },
  {
    key:            'elmundo_portada',
    label:          'El Mundo — Portada',
    url:            'https://e00-elmundo.uecdn.es/rss/portada.xml',
    type:           'rss',
    category:       'ACTUALIDAD',
    spainCategory:  'ACTUALIDAD_ES',
    language:       'es',
    credibility:    0.84,
    refreshMinutes: 20,
    active:         true,
  },
  {
    key:            'elmundo_cultura',
    label:          'El Mundo — Cultura',
    url:            'https://e00-elmundo.uecdn.es/rss/cultura.xml',
    type:           'rss',
    category:       'CULTURA',
    spainCategory:  'CULTURA_ES',
    language:       'es',
    credibility:    0.82,
    refreshMinutes: 30,
    active:         true,
  },
  {
    key:            'lavanguardia_portada',
    label:          'La Vanguardia',
    url:            'https://www.lavanguardia.com/rss/home.xml',
    type:           'rss',
    category:       'ACTUALIDAD',
    spainCategory:  'ACTUALIDAD_ES',
    language:       'es',
    credibility:    0.86,
    refreshMinutes: 20,
    active:         true,
  },
  {
    key:            'lavanguardia_politica',
    label:          'La Vanguardia — Política',
    url:            'https://www.lavanguardia.com/rss/politica.xml',
    type:           'rss',
    category:       'POLITICA',
    spainCategory:  'POLITICA_ES',
    language:       'es',
    credibility:    0.86,
    refreshMinutes: 25,
    active:         true,
  },
  {
    key:            'abc_portada',
    label:          'ABC — Portada',
    url:            'https://www.abc.es/rss/feeds/abc_EspanaEspaña.xml',
    type:           'rss',
    category:       'POLITICA',
    spainCategory:  'POLITICA_ES',
    language:       'es',
    credibility:    0.82,
    refreshMinutes: 25,
    active:         true,
  },
  {
    key:            'abc_cultura',
    label:          'ABC — Cultura',
    url:            'https://www.abc.es/rss/feeds/abc_CulturaCultura.xml',
    type:           'rss',
    category:       'CULTURA',
    spainCategory:  'CULTURA_ES',
    language:       'es',
    credibility:    0.80,
    refreshMinutes: 30,
    active:         true,
  },

  // ── SPORTS ────────────────────────────────────────────────────────────────
  {
    key:            'marca_futbol',
    label:          'Marca — Fútbol',
    url:            'https://www.marca.com/rss/futbol.xml',
    type:           'rss',
    category:       'DEPORTES',
    spainCategory:  'DEPORTE_ES',
    language:       'es',
    credibility:    0.83,
    refreshMinutes: 15,
    active:         true,
  },
  {
    key:            'as_futbol_es',
    label:          'AS — Fútbol Español',
    url:            'https://as.com/rss/tags/liga_espanola.xml',
    type:           'rss',
    category:       'DEPORTES',
    spainCategory:  'DEPORTE_ES',
    language:       'es',
    credibility:    0.81,
    refreshMinutes: 15,
    active:         true,
  },
  {
    key:            'mundo_deportivo',
    label:          'Mundo Deportivo',
    url:            'https://www.mundodeportivo.com/rss/home.xml',
    type:           'rss',
    category:       'DEPORTES',
    spainCategory:  'DEPORTE_ES',
    language:       'es',
    credibility:    0.80,
    refreshMinutes: 15,
    active:         true,
  },
  {
    key:            'sport_futbol',
    label:          'Sport — Fútbol',
    url:            'https://www.sport.es/es/rss/rss.xml',
    type:           'rss',
    category:       'DEPORTES',
    spainCategory:  'DEPORTE_ES',
    language:       'es',
    credibility:    0.78,
    refreshMinutes: 20,
    active:         true,
  },

  // ── REGIONAL ─────────────────────────────────────────────────────────────
  {
    key:            'lavoz_galicia',
    label:          'La Voz de Galicia',
    url:            'https://www.lavozdegalicia.es/rss/index.xml',
    type:           'rss',
    category:       'ACTUALIDAD',
    spainCategory:  'LA_PLAZA',
    language:       'es',
    credibility:    0.80,
    refreshMinutes: 30,
    active:         true,
  },
  {
    key:            'diario_sevilla',
    label:          'Diario de Sevilla',
    url:            'https://www.diariodesevilla.es/rss/section/portada',
    type:           'rss',
    category:       'ACTUALIDAD',
    spainCategory:  'LA_PLAZA',
    language:       'es',
    credibility:    0.76,
    refreshMinutes: 30,
    active:         true,
  },
  {
    key:            'heraldo_aragon',
    label:          'Heraldo de Aragón',
    url:            'https://www.heraldo.es/rss/',
    type:           'rss',
    category:       'ACTUALIDAD',
    spainCategory:  'LA_PLAZA',
    language:       'es',
    credibility:    0.76,
    refreshMinutes: 30,
    active:         true,
  },
  {
    key:            'levante_emv',
    label:          'Levante EMV',
    url:            'https://www.levante-emv.com/rss/',
    type:           'rss',
    category:       'ACTUALIDAD',
    spainCategory:  'LA_PLAZA',
    language:       'es',
    credibility:    0.74,
    refreshMinutes: 30,
    active:         true,
  },

  // ── TRENDING / GOOGLE ─────────────────────────────────────────────────────
  {
    key:            'google_trends_es',
    label:          'Google Trends — España',
    url:            'https://trends.google.es/trending/rss?geo=ES',
    type:           'rss',
    category:       'ACTUALIDAD',
    spainCategory:  'LA_PLAZA',
    language:       'es',
    credibility:    0.65,   // trend signals, not hard news
    refreshMinutes: 20,
    active:         true,
  },
]

// Lookup helpers
export const SPAIN_SOURCE_MAP = Object.fromEntries(SPAIN_SOURCES.map(s => [s.key, s]))

export function getActiveSpainSources() {
  return SPAIN_SOURCES.filter(s => s.active)
}

export function getSpainSourcesByCategory(spainCategory) {
  return SPAIN_SOURCES.filter(s => s.active && s.spainCategory === spainCategory)
}
